"""
Django settings for stemiot_softwares project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o*tr8ayot3x2d*w5n^)t5kapy*w*3m4!)$gxm7i03_d$3#lasp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stemiotApp'
]

JAZZMIN_SETTINGS = {
    # "site_logo": "assets/img/logo1.png",
    "login-logo": None,
    # "custom_css": "css/custom_admin.css",
    # "custom_css": "admin/css/admin_custom.css",
    "site_icon": "static/assets/img/logo1.png",
    "site_title": "Stemiot Softwares Admin",
    "site_header": "Stemiot Softwares Management",
    "site_brand": "StemiotSoftwares",
    "site_brand_link": "/",
    "welcome_sign": "Welcome to Stemiot Softwares Admin Panel",
    "copyright": " Stemiot Softwares",

    "search_model": [ "StemiotApp.Client"],

    # ✅ Adding Home Button in Sidebar
    "topmenu_links": [
        {"name": "Home", "url": "/", "icon": "fas fa-home", "show_sidebar": True},
        {"model": "StemiotApp.Client"},
    ],

    "usermenu_links": [
        {"name": "Homepage", "url": "/", "new_window": False},  # Homepage Link in User Menu
    ],

    "icons": {
        "FiloArtsPlus.Client": "fas fa-users",
        "auth.User": "fas fa-user",
    },

    # ✅ Controlling Sidebar Order
    "order_with_respect_to": [
        "Home",
        # "FiloArtsPlus.Drawing",
        "FiloArtsPlus.Client",
        # "FiloArtsPlus.Transaction",
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stemiot_softwares.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stemiot_softwares.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "static/staticfiles")  # Ensure this is a valid path

# Additional static files directories (for development)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
