# Generated by Django 5.1.3 on 2025-06-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=50)),
                ('client_phone', models.IntegerField(max_length=13)),
                ('client_message', models.TextField()),
            ],
        ),
    ]
